### ISSUE TITLE
Build for OSMC Vero V

### ISSUE THREAD

**Issue by tvass** [notspiff/visualization.spectrum#119]
Hi there,
Would it possible to have build for [OSMC Vero V](https://osmc.tv/wiki/vero-v/technical-specifications/) ?
Let me know what you think please,
Thomas

**Comment by chewitt** [comment]
That's a question for the OSMC devs to answer, as they are responsible for building and publishing Kodi binary add-ons for their distro (same as all Linux distros).

**Comment by tvass** [comment]
Hi @chewitt 
Yeah. Of course. I will try to reach out.
(i was confused  this morning - lack of coffee -  with the builds available at [Kodi](https://kodi.tv/addons/nexus/visualization.spectrum/) and your release page (source) at [GH](https://github.com/xbmc/visualization.spectrum/releases).
Sorry for the noise.
Thanks
