### ISSUE TITLE
Build error with latest kodi-nexus

### ISSUE THREAD

**Issue by coffeinflash** [notspiff/visualization.spectrum#92]
I get the following error while building against the latest git-tree from kodi-Nexus:

`[   53s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build'
[   53s] cd "/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build" && /usr/bin/cmake -E cmake_depends "Unix Makefiles" "/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475" "/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475" "/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build" "/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build" "/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build/CMakeFiles/visualization.spectrum.dir/DependInfo.cmake"
[   53s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build'
[   53s] /usr/bin/make  -f CMakeFiles/visualization.spectrum.dir/build.make CMakeFiles/visualization.spectrum.dir/build
[   56s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build'
[   56s] [ 50%] Building CXX object CMakeFiles/visualization.spectrum.dir/src/opengl_spectrum.cpp.o
[   56s] /usr/bin/g++-10 -DADDON_GLOBAL_VERSION_FILESYSTEM_USED -DADDON_GLOBAL_VERSION_GUI_USED -DADDON_GLOBAL_VERSION_MAIN_USED -DADDON_INSTANCE_VERSION_VISUALIZATION_USED -DBUILD_KODI_ADDON -DHAS_GL=1 -Dvisualization_spectrum_EXPORTS -I/usr/include/glm -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -pthread -flto -O2 -g -DNDEBUG -fPIC   -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -std=c++17 -MD -MT CMakeFiles/visualization.spectrum.dir/src/opengl_spectrum.cpp.o -MF CMakeFiles/visualization.spectrum.dir/src/opengl_spectrum.cpp.o.d -o CMakeFiles/visualization.spectrum.dir/src/opengl_spectrum.cpp.o -c "/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/src/opengl_spectrum.cpp"
[   56s] /home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/src/opengl_spectrum.cpp:51:8: error: 'bool CVisualizationSpectrum::Start(int, int, int, std::string)' marked 'override', but does not override
[   56s]    51 |   bool Start(int channels, int samplesPerSec, int bitsPerSample, std::string songName) override;
[   56s]       |        ^~~~~
[   56s] /home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/src/opengl_spectrum.cpp:54:8: error: 'void CVisualizationSpectrum::AudioData(const float*, int, float*, int)' marked 'override', but does not override
[   56s]    54 |   void AudioData(const float* audioData, int audioDataLength, float* freqData, int freqDataLength) override;
[   56s]       |        ^~~~~~~~~
[   56s] make[2]: *** [CMakeFiles/visualization.spectrum.dir/build.make:79: CMakeFiles/visualization.spectrum.dir/src/opengl_spectrum.cpp.o] Error 1
[   56s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/kodi.binary-addons-visualization.spectrum-20.1.0.20220916T160909~8d01475/build'
[   56s] make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/visualization.spectrum.dir/all] Error 2
[   56s] make: *** [Makefile:159: all] Error 2
[   56s] error: Bad exit status from /var/tmp/rpm-tmp.5fx695 (%build)`

The full build log can be found here: https://build.opensuse.org/package/live_build_log/home:Herbster0815:HTPC/kodi.binary-addons-visualization.spectrum/openSUSE_Leap_15.4/x86_64

**Comment by AlwinEsch** [comment]
The release was a bit delayed, was now come in and should work in latest released version.
